### ISSUE TITLE
User.save not found

### ISSUE THREAD

**Issue by bigluck** [brikteknologier/seraph-model#69]
I'm having this problem:

``` coffeescript
db = require('seraph') 'http://localhost:7474'
model = require 'seraph-model'
User = model db, 'Iser'

a = User

User.read 3, (err, user) ->
    user.test = "tested"
    console.log "Is the same? ", if User is a then "yes" else "no"
    User.save user, (err, user) ->
        console.log "Updated", arguments
```

But:

``` sh
23:56:00 web.1  | Is the same:  no
23:56:00 web.1  | TypeError: Object false has no method 'save'
23:56:00 web.1  |   at /Users/bigluck/Desktop/graph/app.coffee:43:7
23:56:00 web.1  |   at Model.coalesceAndCompute (/Users/bigluck/Desktop/graph/node_modules/seraph-model/lib/read.js:111:28)
23:56:00 web.1  |   at /Users/bigluck/Desktop/graph/node_modules/seraph-model/lib/read.js:203:26
23:56:00 web.1  |   at /Users/bigluck/Desktop/graph/node_modules/seraph/lib/seraph.js:387:5
23:56:00 web.1  |   at Seraph.<anonymous> (/Users/bigluck/Desktop/graph/node_modules/seraph/lib/seraph.js:335:7)
23:56:00 web.1  |   at /Users/bigluck/Desktop/graph/node_modules/seraph/lib/seraph.js:183:7
23:56:00 web.1  |   at [object Object]._onTimeout (/Users/bigluck/Desktop/graph/node_modules/seraph/node_modules/underscore/underscore.js:647:47)
23:56:00 web.1  |   at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

What's wrong?

**Comment by TylerMatteo** [comment]
I had a similar problem but not sure if it's for the same reason. To have access to read I had to initialize my model like this or else the function was nested inside db.node 

    var User = model(db, 'User').db.node

I'm concerned that I'm losing parts of the object by initializing this way but I'm not sure how else to get around this issue. As for my db connection, I initialize it in another file and reference it in my models. Here's what it looks like.

    var db = require("seraph")({
      server: "https://db-???????????????.graphenedb.com:24780",
      user: "FakeName",
      pass: "FakePass"
    });
