### ISSUE TITLE
Calling model#where with include results in error relating to method "compute", but included model has no computed properties

### ISSUE THREAD

**Issue by lsocrate** [brikteknologier/seraph-model#78]
I am calling a model#where passing an included model that has no computed properties, but I get an error relating to the method "compute". I have absolutely no idea what is happening.

The code:
```js
// The models
var User = require('seraph_model')(db, 'User');
User.schema = {
  email: String,
  hashedPassword: String
};
User.on("prepare", callbackForPasswordHashing)

var Token = require('seraph_model')(db, 'Token');
Token.schema = {
  hash: String
};
Token.on("prepare", callbackForHashCreation);

User.compose(Token, "tokens", "has_token", { many: true })

// The call
Token.where({ hash: "abcedf" }, { include: [ { model: "User" ] }, cb)
```

The error stack:
```
     Uncaught TypeError: Object User has no method 'compute'
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/lib/read.js:160:27
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:86:13
      at Array.forEach (native)
      at _forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:26:24)
      at Object.async.forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:85:9)
      at collectIncludes (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/lib/read.js:157:13)
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:454:21
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:185:13
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:86:13
      at Array.forEach (native)
      at _forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:26:24)
      at async.forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:85:9)
      at _asyncMap (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:184:9)
      at Object.map (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:168:23)
      at Object.async.parallel (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:452:19)
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/lib/read.js:169:11
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:185:13
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:86:13
      at Array.forEach (native)
      at _forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:26:24)
      at async.forEach (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:85:9)
      at _asyncMap (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:184:9)
      at Object.map (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/node_modules/async/lib/async.js:168:23)
      at Model.coalesceAndCompute (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/lib/read.js:118:9)
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph-model/lib/read.js:212:26
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph/lib/seraph.js:396:5
      at Seraph.<anonymous> (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph/lib/seraph.js:336:7)
      at /home/lsocrate/Projects/futuredeck/api/node_modules/seraph/lib/seraph.js:184:7
      at null._onTimeout (/home/lsocrate/Projects/futuredeck/api/node_modules/seraph/node_modules/underscore/underscore.js:647:47)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by lsocrate** [comment]
Found my mistake. I was using the wrong syntax on the `include`.
